name: Multi-Module Build and Publish

on:
  push:
    tags:
      - 'module-1-*'
      - 'module-2-*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and publish Module 1
        if: startsWith(github.ref, 'refs/tags/module-1-')
        run: |
          ./gradlew :module-1:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Module 2
        if: startsWith(github.ref, 'refs/tags/module-2-')
        run: |
          ./gradlew :module-2:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
